name: Comment on Opened Issues

on:
  issues:
    types:
      - opened

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Comment on Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Replace this with your desired comment message
          comment_message="Thank you for opening this pull request! We will review it shortly."

          # Get the pull request number from the event payload
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          # Post a comment on the pull request
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$pr_number/comments \
            -d "{\"body\": \"$comment_message\"}"
